#!/usr/bin/env bash
# Displays numbers from 1 to 100 in a list format.
#   Displays "FizzBuzz" if the number is a multiple of 3 and 5.
#   Displays "Fizz" if the number is a multiple of 3.
#   Displays "Buzz" if the number is a multiple of 5.
#   Otherwise, it displays the number.

for ((i=1; i<=100; i++))
do
    if ((i % 3 == 0)) && ((i % 5 == 0))
    then
        echo "FizzBuzz"
    elif ((i % 3 == 0))
    then
        echo "Fizz"
    elif ((i % 5 == 0))
    then
        echo "Buzz"
    else
        echo "$i"
    fi
done