#!/usr/bin/env bash
#A script that iterates 10 times and:
#       1. displays `bad luck` for the 4th loop iteration
#       2. displays `good luck` for the 8th loop iteration
#       3. displays "Best School" for the other iterations

count=0

while [ $count -lt 10 ]
do
    if [ $count -eq 3 ]
    then
        echo "bad luck"
    elif [ $count -eq 7 ]
    then
        echo "good luck"
    else
        echo "Best School"
    fi
    (( count++ ))
done