#!/usr/bin/env bash

# Update the /etc/hosts file to change the IP address mappings
sudo sed -i 's/127\.0\.0\.1/127\.0\.0\.2/g' /etc/hosts
sudo sed -i 's/facebook\.com/8\.8\.8\.8/g' /etc/hosts

# Clear the DNS cache
sudo systemd-resolve --flush-caches
